env:
  commonjs: true
  es2020: true
  node: true
extends:
  - google
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - 4
    - "SwitchCase": 1
  object-curly-spacing:
    - error
    - always
